### PR TITLE
Adds pet names

### PR DESCRIPTION
**Pull request by Coolomina**
Sorry for the sanitize function fokes, did not want to add a shitty external library.

Also, adds `mamadisimo`

### CODE REVIEW

**Comment by jcagarcia** [comment]
Waiting for this feature 👍

**Review by jcagarcia — APPROVED** [review]

**Comment by Coolomina** [comment]
I'm going to wait for #3 to be merged, meanwhile marking it as WIP

**Comment by pollosp** [comment]
🤔

**Review by pollosp — COMMENTED** [review]
Are we going to maintain 2 lists? should we have this in a separated json and read json from here?

**Comment by Coolomina** [comment]
@pollosp Nope, was waiting for #3 to be merged to get the JSON out of that.

**Review by pollosp — APPROVED** [review]

**Pull request merged**
