### PR TITLE
Actualizar con nuevos saludos

### PR DESCRIPTION
**Pull request by jajimgme**
Astro y Fragata añadidos

### CODE REVIEW

**Comment by pollosp** [comment]
@jajimgme could you use the new tooling proposed by @MiguelBel  ? Thanks  for the contribution :)

**Comment by jajimgme** [comment]
> 
> 
> @jajimgme could you use the new tooling proposed by @MiguelBel ? Thanks for the contribution :)

Sorry, I don't have ruby installed in my computer :( Fragata and astro will remain unincluded.

**Comment by Coolomina** [comment]
Please add them on the https://github.com/pollosp/saludos/blob/master/saludos.json. THanks!

**Comment by pollosp** [comment]
I have added some docker instructions ;)

**Pull request closed without merging**
